### ISSUE TITLE
ffmpegcv.VideoCaptureNV  is not working

### ISSUE THREAD

**Issue by muhammetp** [chenxinfeng4/ffmpegcv#1]
my env
cuda 11.3
cudnn 8.2.1

pip install tensorflow-gpu==2.7.0

pip install torch==1.12.0+cu113 torchaudio==0.12.0+cu113 torchvision==0.13.0+cu113 --extra-index-url https://download.pytorch.org/whl/cu113

opencv-contrib-python          4.5.3.56
ffmpeg version N-87353-g183fd30 Copyright (c) 2000-2017 the FFmpeg developers
libavutil      55. 76.100 / 55. 76.100
libavcodec     57.106.101 / 57.106.101
libavformat    57. 82.101 / 57. 82.101
libavdevice    57.  8.101 / 57.  8.101
libavfilter     6.105.100 /  6.105.100
libswscale      4.  7.103 /  4.  7.103
libswresample   2.  8.100 /  2.  8.100
libpostproc    54.  6.100 / 54.  6.100

when i change to ffmpegcv.VideoCapture it read all frame. i think there is a problem with cuda config

**Comment by chenxinfeng4** [comment]
It may not be a problem of 'ffmpegcv'. However, it should be the problem of 'ffmpeg', because the original/official release of ffmpeg didn't include the NVIDIA GPU DECODER/ENCODER. Only the Microsoft Windows ffmpeg includes NVIDIA DECODER/ENCODER, but not windows.

**Comment by chenxinfeng4** [comment]
It may not be a problem of 'ffmpegcv'. However, it should be the problem of 'ffmpeg', because the original/official release of ffmpeg didn't include the NVIDIA GPU DECODER/ENCODER. Only the Microsoft Windows ffmpeg includes NVIDIA DECODER/ENCODER, but not windows.

**Comment by chenxinfeng4** [comment]
It may not be a problem of 'ffmpegcv'. However, it should be the problem of 'ffmpeg', because the original/official release of ffmpeg didn't include the NVIDIA GPU DECODER/ENCODER. Only the Microsoft Windows ffmpeg includes NVIDIA DECODER/ENCODER, but not windows.

**Comment by chenxinfeng4** [comment]
It may not be a problem of 'ffmpegcv'. However, it should be the problem of 'ffmpeg', because the original/official release of ffmpeg didn't include the NVIDIA GPU DECODER/ENCODER. Only the Microsoft Windows ffmpeg includes NVIDIA DECODER/ENCODER.

> The Linux ffmpeg didn't orginally support NVIDIA accelerate. To use ffmepgcv.VideoCaptureNV, please re-compile the ffmpeg by yourself. See the [link](https://docs.nvidia.com/video-technologies/video-codec-sdk/ffmpeg-with-nvidia-gpu/)

**Comment by chenxinfeng4** [comment]
To check whether ffmpeg can use NVIDIA GPU or not, please run

> ffmpeg -i INPUT.mp4 -c:v h264_nvenc   h264.mp4    #Test for NVIDIA ENCODER
> ffmpeg -c:v h264_cuvid -i h264.mp4 OUTPUT.mp4   #Test for NVIDIA DECODER

**Comment by muhammetp** [comment]
Ok thank you

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by muhammetp** [comment]
hi chen

i replied to  email but it looks like not inserted here as comment

**Comment by muhammetp** [comment]
Hi chen

Both of them(encoder and decoder testing cmds) look like run properly. In this case, do still I need to compile from the source of the FFmpeg?

This is the output of the encoder


C:\Users\mpak8\Downloads\test_clips>ffmpeg -i indoor.mp4 -c:v h264_nvenc h264.mp4

ffmpeg version N-87353-g183fd30 Copyright (c) 2000-2017 the FFmpeg developers

  built with gcc 7.2.0 (GCC)

  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib

  libavutil      55. 76.100 / 55. 76.100
  libavcodec     57.106.101 / 57.106.101
  libavformat    57. 82.101 / 57. 82.101
  libavdevice    57.  8.101 / 57.  8.101
  libavfilter     6.105.100 /  6.105.100
  libswscale      4.  7.103 /  4.  7.103
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'indoor.mp4':

  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.51.100

  Duration: 00:00:20.04, start: 0.000000, bitrate: 2666 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 2532 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)

    Metadata:
      handler_name    : VideoHandler

    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler

Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_nvenc))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))

Press [q] to stop, [?] for help

Output #0, mp4, to 'h264.mp4':

  Metadata:

    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.82.101

    Stream #0:0(und): Video: h264 (h264_nvenc) (Main) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=-1--1, 2000 kb/s, 25 fps, 12800 tbn, 25 tbc (default)

    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc57.106.101 h264_nvenc

    Side data:
      cpb: bitrate max/min/avg: 0/0/2000000 buffer size: 4000000 vbv_delay: -1
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 69 kb/s (default)

    Metadata:
      handler_name    : SoundHandler
      encoder         : Lavc57.106.101 aac

frame=  501 fps=327 q=16.0 Lsize=    4358kB time=00:00:20.01 bitrate=1783.7kbits/s speed=13.1x

video:4172kB audio:171kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.346695%

[aac @ 0000000000f7dd20] Qavg: 343.085

 

This the output of decoder

 

C:\Users\mpak8\Downloads\test_clips>ffmpeg -c:v h264_cuvid -i h264.mp4 OUTPUT.mp4

ffmpeg version N-87353-g183fd30 Copyright (c) 2000-2017 the FFmpeg developers

  built with gcc 7.2.0 (GCC)

  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib

  libavutil      55. 76.100 / 55. 76.100
  libavcodec     57.106.101 / 57.106.101
  libavformat    57. 82.101 / 57. 82.101
  libavdevice    57.  8.101 / 57.  8.101
  libavfilter     6.105.100 /  6.105.100
  libswscale      4.  7.103 /  4.  7.103
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'h264.mp4':

  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.82.101

  Duration: 00:00:20.04, start: 0.000000, bitrate: 1781 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 1705 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)

    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 69 kb/s (default)

    Metadata:
      handler_name    : SoundHandler

Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_cuvid) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))

Press [q] to stop, [?] for help

[libx264 @ 0000000002cb0a20] using SAR=1/1
[libx264 @ 0000000002cb0a20] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0000000002cb0a20] profile High, level 4.0
[libx264 @ 0000000002cb0a20] 264 - core 152 r2851 ba24899 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=18 lookahead_threads=3 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00

Output #0, mp4, to 'OUTPUT.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.82.101
    Stream #0:0(und): Video: h264 (libx264) (avc1 / 0x31637661), nv12, 1920x1080 [SAR 1:1 DAR 16:9], q=-1--1, 25 fps, 12800 tbn, 25 tbc (default)

    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc57.106.101 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 69 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      encoder         : Lavc57.106.101 aac

frame=  505 fps=108 q=-1.0 Lsize=    3695kB time=00:00:20.08 bitrate=1507.4kbits/s dup=4 drop=0 speed=4.31x
video:3507kB audio:170kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.504136%
[libx264 @ 0000000002cb0a20] frame I:3     Avg QP:15.98  size: 92048
[libx264 @ 0000000002cb0a20] frame P:189   Avg QP:18.11  size: 12541
[libx264 @ 0000000002cb0a20] frame B:313   Avg QP:23.72  size:  3016
[libx264 @ 0000000002cb0a20] consecutive B-frames: 12.5%  6.3% 25.0% 56.2%
[libx264 @ 0000000002cb0a20] mb I  I16..4: 32.9% 43.5% 23.6%
[libx264 @ 0000000002cb0a20] mb P  I16..4:  4.4%  4.3%  0.4%  P16..4: 17.5%  3.8%  1.9%  0.0%  0.0%    skip:67.6%
[libx264 @ 0000000002cb0a20] mb B  I16..4:  0.4%  0.6%  0.1%  B16..8: 20.3%  0.7%  0.1%  direct: 0.3%  skip:77.6%  L0:47.8% L1:51.1% BI: 1.1%

[libx264 @ 0000000002cb0a20] 8x8 transform intra:48.0% inter:68.8%
[libx264 @ 0000000002cb0a20] coded y,uvDC,uvAC intra: 26.4% 57.0% 10.8% inter: 2.8% 4.9% 0.1%
[libx264 @ 0000000002cb0a20] i16 v,h,dc,p: 18% 40% 22% 20%
[libx264 @ 0000000002cb0a20] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 20% 29% 36%  2%  2%  3%  3%  2%  3%
[libx264 @ 0000000002cb0a20] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 23% 32% 16%  4%  6%  4%  7%  4%  4%
[libx264 @ 0000000002cb0a20] i8c dc,h,v,p: 50% 26% 19%  4%
[libx264 @ 0000000002cb0a20] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0000000002cb0a20] ref P L0: 77.3%  4.9% 13.7%  4.0%
[libx264 @ 0000000002cb0a20] ref B L0: 85.9% 12.3%  1.8%
[libx264 @ 0000000002cb0a20] ref B L1: 96.5%  3.5%
[libx264 @ 0000000002cb0a20] kb/s:1421.91
[aac @ 0000000002a63740] Qavg: 195.358

**Comment by chenxinfeng4** [comment]
The ffmpeg looks fine, and no need to recompile it. 

How does this code work??
```python
vid = ffmpegcv.VideoCaptureNV('h264.mp4')
ret, image = vid.read()
```

**Comment by muhammetp** [comment]
video captured but frame is not required 

![image](https://user-images.githubusercontent.com/11661283/187066481-fe1e4478-3175-4ebe-b85c-4513a2a0e2f8.png)

**Comment by chenxinfeng4** [comment]
Can you show me the version of 'ffmpegcv'? I will check that in windows.

**Comment by chenxinfeng4** [comment]
Here is my test in a new windows machine, which works just fine. ffmpegcv==0.2.3 
![image](https://user-images.githubusercontent.com/17546446/187130971-44eb507f-bc49-4b17-be63-67994494609a.png)

Please check the ffmpeg like below. 
![image](https://user-images.githubusercontent.com/17546446/187131265-a0ef9b42-5f9b-4ef1-965d-f538edd13fa9.png)

**Comment by muhammetp** [comment]
hi chen

**Comment by muhammetp** [comment]
ffmpeg version

![image](https://user-images.githubusercontent.com/11661283/189281036-ab4363bd-2ac8-4746-9ba8-f390fba5414d.png)

**Comment by chenxinfeng4** [comment]
**Your ffmpeg didn't enable nvidia-encoder decoder yet.**  Please download a new version.

![image](https://user-images.githubusercontent.com/17546446/189281287-38cf62c6-85df-480b-a138-38fbca357cfe.png)

**Comment by muhammetp** [comment]
can you suggest specific version for ffmpeg and ffmpegcv . 
secondly, before installing ffmpeg again, should i delete the ffmpegcv

**Comment by chenxinfeng4** [comment]
conda install ffmpeg

```
(base) PS C:\Users\w> conda install ffmpeg
...
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     ffmpeg.exe                                         0.0.0.0    D:\L_Anaconda\Library\bin\ffmpeg.exe


(base) PS C:\Users\w>  D:\L_Anaconda\Library\bin\ffmpeg.exe
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
```
You can copy that ffmpeg.exe to your system path.

**Comment by muhammetp** [comment]
pip install canbe used insterad of conda install?

**Comment by chenxinfeng4** [comment]
conda install ffmpeg #it will download ffmpeg, not ffmpegcv
pip install ffmpegcv  #it will download ffmpegcv, not ffmpeg

Both commands are need for setup.

**Comment by muhammetp** [comment]
i mean pip install ffmpeg

**Comment by chenxinfeng4** [comment]
No, "pip install ffmpeg" is not an official "ffmpeg". It's an python API connect to your local ffmpeg.exe. 

 "pip install ffmpeg" is not need to use ffmpegcv.

**Comment by muhammetp** [comment]
to get ffmpeg.exe you pointed out

**Comment by muhammetp** [comment]
i copied everthing from anaconda ffmpeg installation not only exe. now its working thank you

**Comment by muhammetp** [comment]
Hi chen

Both of them looks like run properly. In this case, still I need compile from source of the ffmpeg?
This the ouput of encoder

C:\Users\mpak8\Downloads\test_clips>ffmpeg -i indoor.mp4 -c:v h264_nvenc h264.mp4
ffmpeg version N-87353-g183fd30 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 76.100 / 55. 76.100
  libavcodec     57.106.101 / 57.106.101
  libavformat    57. 82.101 / 57. 82.101
  libavdevice    57.  8.101 / 57.  8.101
  libavfilter     6.105.100 /  6.105.100
  libswscale      4.  7.103 /  4.  7.103
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'indoor.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.51.100
  Duration: 00:00:20.04, start: 0.000000, bitrate: 2666 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 2532 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_nvenc))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
Output #0, mp4, to 'h264.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.82.101
    Stream #0:0(und): Video: h264 (h264_nvenc) (Main) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=-1--1, 2000 kb/s, 25 fps, 12800 tbn, 25 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc57.106.101 h264_nvenc
    Side data:
      cpb: bitrate max/min/avg: 0/0/2000000 buffer size: 4000000 vbv_delay: -1
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 69 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      encoder         : Lavc57.106.101 aac
frame=  501 fps=327 q=16.0 Lsize=    4358kB time=00:00:20.01 bitrate=1783.7kbits/s speed=13.1x
video:4172kB audio:171kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.346695%
[aac @ 0000000000f7dd20] Qavg: 343.085

This the output of decoder

C:\Users\mpak8\Downloads\test_clips>ffmpeg -c:v h264_cuvid -i h264.mp4 OUTPUT.mp4
ffmpeg version N-87353-g183fd30 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 76.100 / 55. 76.100
  libavcodec     57.106.101 / 57.106.101
  libavformat    57. 82.101 / 57. 82.101
  libavdevice    57.  8.101 / 57.  8.101
  libavfilter     6.105.100 /  6.105.100
  libswscale      4.  7.103 /  4.  7.103
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'h264.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.82.101
  Duration: 00:00:20.04, start: 0.000000, bitrate: 1781 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 1705 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 69 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_cuvid) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 0000000002cb0a20] using SAR=1/1
[libx264 @ 0000000002cb0a20] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0000000002cb0a20] profile High, level 4.0
[libx264 @ 0000000002cb0a20] 264 - core 152 r2851 ba24899 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=18 lookahead_threads=3 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'OUTPUT.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.82.101
    Stream #0:0(und): Video: h264 (libx264) (avc1 / 0x31637661), nv12, 1920x1080 [SAR 1:1 DAR 16:9], q=-1--1, 25 fps, 12800 tbn, 25 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc57.106.101 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 69 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      encoder         : Lavc57.106.101 aac
frame=  505 fps=108 q=-1.0 Lsize=    3695kB time=00:00:20.08 bitrate=1507.4kbits/s dup=4 drop=0 speed=4.31x
video:3507kB audio:170kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.504136%
[libx264 @ 0000000002cb0a20] frame I:3     Avg QP:15.98  size: 92048
[libx264 @ 0000000002cb0a20] frame P:189   Avg QP:18.11  size: 12541
[libx264 @ 0000000002cb0a20] frame B:313   Avg QP:23.72  size:  3016
[libx264 @ 0000000002cb0a20] consecutive B-frames: 12.5%  6.3% 25.0% 56.2%
[libx264 @ 0000000002cb0a20] mb I  I16..4: 32.9% 43.5% 23.6%
[libx264 @ 0000000002cb0a20] mb P  I16..4:  4.4%  4.3%  0.4%  P16..4: 17.5%  3.8%  1.9%  0.0%  0.0%    skip:67.6%
[libx264 @ 0000000002cb0a20] mb B  I16..4:  0.4%  0.6%  0.1%  B16..8: 20.3%  0.7%  0.1%  direct: 0.3%  skip:77.6%  L0:47.8% L1:51.1% BI: 1.1%
[libx264 @ 0000000002cb0a20] 8x8 transform intra:48.0% inter:68.8%
[libx264 @ 0000000002cb0a20] coded y,uvDC,uvAC intra: 26.4% 57.0% 10.8% inter: 2.8% 4.9% 0.1%
[libx264 @ 0000000002cb0a20] i16 v,h,dc,p: 18% 40% 22% 20%
[libx264 @ 0000000002cb0a20] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 20% 29% 36%  2%  2%  3%  3%  2%  3%
[libx264 @ 0000000002cb0a20] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 23% 32% 16%  4%  6%  4%  7%  4%  4%
[libx264 @ 0000000002cb0a20] i8c dc,h,v,p: 50% 26% 19%  4%
[libx264 @ 0000000002cb0a20] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0000000002cb0a20] ref P L0: 77.3%  4.9% 13.7%  4.0%
[libx264 @ 0000000002cb0a20] ref B L0: 85.9% 12.3%  1.8%
[libx264 @ 0000000002cb0a20] ref B L1: 96.5%  3.5%
[libx264 @ 0000000002cb0a20] kb/s:1421.91
[aac @ 0000000002a63740] Qavg: 195.358

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by muhammetp** [comment]
Where I find this version of ffmpeg?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
