### ISSUE TITLE
Does ffmpegcv preserve audio on video write?

### ISSUE THREAD

**Issue by kanhirun** [chenxinfeng4/ffmpegcv#10]
On OpenCV, one of the problems with `VideoWriter` is that we lose audio as part of the process.

Wondering if ffmpegcv addresses this issue?

**Comment by kanhirun** [comment]
@chenxinfeng4 ☝️

**Comment by chenxinfeng4** [comment]
Online copy the audio is hard. It's much easy to use `ffmpeg` to do the offline audio merge.

```bash
ffmpeg -i A.mp4 -i B.mp4 -map 0:a -map 1:v -c:a copy -c:v copy C.mp4
```
