### ISSUE TITLE
How should I extract all of the frames from a video?

### ISSUE THREAD

**Issue by NevermindNilas** [chenxinfeng4/ffmpegcv#11]
Hello, excuse me if this is a very basic question, I am still learning.
I tried an approach that was similar to this:

```python
import ffmpegcv
vfile_in = 'A.mp4'
vfile_out = 'A_h264.mp4'
vidin = ffmpegcv.VideoCapture(vfile_in)
vidout = ffmpegcv.VideoWriter(vfile_out)

with vidin, vidout:
    for frame in vidin:
        vidout.write(frame)
```

but instead of `vidout = ffmpegcv.VideoWriter(vfile_out)` I wanted to have this: 

```python
vidout = ffmpegcv.VideoWriter(os.path.join(output_temp, 'frame_' + str(i).zfill(6) + "." + image_extension))
```

Sadly the output, whilst having the correct name it didn't maintain or parse the image data ( it didn't have any height, width and it even showed up as as corrupted image in Windows ).

Whilst I am here, I'd like to know if there's a way, similar to my current FFMPEG approach to speeds things up
```python
ffmpeg_command = f'{ffmpeg_path} -i "{video_file}" -vsync 0 -qmin 1 -qscale:v 1 -v quiet -stats "{output_temp}"/"{frame_name}"."{image_extension}'
```

Particularly, adding " -vsync 0 -qmin 1 -qscale:v 1 " have virtually doubled the performance, granted it has a higher overall size but space isn't an issue, speed is. 

Could this be replicated, and if so how?

And another one, could ffmpegcv support Asynchronous encoding, as in encoding frame by frame so that each time I process a frame ( extract the frames, upscale them and then encode ) I could also have it be encoded without having to wait for all of the images to be upscaled and only then start the encoding. Basically encoding on the go, I guess?

**Comment by MHRosenberg** [comment]
Could you clarify your reply? What use cases are suggests vs not? Thank you!
