### ISSUE TITLE
Using with Raspberry Pi Camera

### ISSUE THREAD

**Issue by SamedBll** [chenxinfeng4/ffmpegcv#13]
I saw the VideoCaptureCAM() function, passing "/dev/video0" to camname doesn't seem to work.
Is there any usage with the camera?

**Comment by chenxinfeng4** [comment]
The VideoCaptureCAM is under-developing. The camero is too hard to use a simple API. Why? The ffmpeg has mutliple API for different platform, and you must specify the FPS/ the resolution/ the stream format before you can connect the camera. Seems not friendly. The VideoCaptureCAM is experimental, the opencv would be better.

I'll release the VideoCaptureCAM in days, and I try my best to make the API friendly and consistent with the VideoCapture. Thanks for your interest.

**Comment by SamedBll** [comment]
I'm just trying, it's called 'simple' after all. By the way, ffmpeg includes codecs at least, OpenCV is not that comfortable. Are there any wrappers written in Python for ffmpeg, yes there are. 

I'm following the project, good luck.
