### ISSUE TITLE
get_info crashes when using a TransportStream container

### ISSUE THREAD

**Issue by tmaoz** [chenxinfeng4/ffmpegcv#14]
Hey,

I started experimenting with ffmpegcv and have come across this issue where when I use a .ts (TransportStream) container, get_info crashes as the XML output from ffprobe does not contain the "nb_frames" field.
When using an mp4 container everything works as expected.

I should point out that I am using Ubuntu 18.04 with ffmpeg version 4.3.2 at the moment and have also tested with ffmpeg 6.0 running on Ubuntu 22.04.

Could you please add a check to only set the field in the video info if it exists in the xml output?

Thanks!

**Comment by tmaoz** [comment]
Thanks!

Well, it does, indeed, work with the ts file now.
However, the addition of the `-count_packets` flag now causes another issue.
In addition to a file input, I also would like to use a looped RTSP input stream. `-count_packets` basically causes ffprobe to get stuck there indefinitely (obviously).

Any idea how I can use an RTSP stream now?

**Comment by chenxinfeng4** [comment]
The rtsp stream reading is another issue. **I have not done that function yet**. If you are desperate in RTSP reading, you can use opencv.


```python
# opencv
import cv2
import os

RTSP_URL = 'rtsp://user:pass@192.168.0.189:554/h264Preview_01_main'

os.environ['OPENCV_FFMPEG_CAPTURE_OPTIONS'] = 'rtsp_transport;udp'

cap = cv2.VideoCapture(RTSP_URL, cv2.CAP_FFMPEG)

if not cap.isOpened():
    print('Cannot open RTSP stream')
    exit(-1)

while True:
    _, frame = cap.read()
    cv2.imshow('RTSP stream', frame)

    if cv2.waitKey(1) == 27:
        break

cap.release()
cv2.destroyAllWindows()
```

Or you can adapt the code in `ffmpeg.VideoCaptureCAM`. Besides, what's your motivion using you `ffmpegcv` than `opencv`.

**Comment by chenxinfeng4** [comment]
I've add the RTMP/RTSP/HTTP stream reading in ffmpegcv just now. Follow the README and try it. This feature is experimental.

```python
import ffmpegcv
cap = ffmpegcv.VideoCaptureStream(stream_url)
while True:
    ret, frame = cap.read()
    if not ret:
        break
    pass
```

**Comment by tmaoz** [comment]
Sure thing, thanks!

I'll test it and report back.

The point is that I want to run ffmpeg on a Tegra device and have compiled my own ffmpeg that supports the HW decoder/encoder on the Tegra. I can't get OpenCV to use my ffmpeg as the python OpenCV comes with its own version of the ffmpeg libs. Thus, ffmpegcv seems like an nice and easy way to switch without changing a lot of code.

**Comment by tmaoz** [comment]
Yeah, that seems so be working great. Thanks!

There are other features I would like to have but you're right, I might just fork the repo and add what I need.
Some things include the ability to select the input codec for streams as well, the ability to add other input config (for example I prefer using TCP transport to UDP for my RTSP streams) etc.
