### ISSUE TITLE
cannot open camera

### ISSUE THREAD

**Issue by sri-wahyuni10** [chenxinfeng4/ffmpegcv#15]
'ffprobe -v quiet -print_format xml -select_streams v:0 -show_format -show_streams "rtsp://ipcam:8554/main"' returned non-zero exit status 1.

can you help me?

**Comment by chenxinfeng4** [comment]
I didn't have a rtsp camera in my hand. It will take a bit long time to figure it out, maybe in next week.

Can you show me your platform information, and the output in your `cmd` or `bash` terminal?
```
> ffprobe -v quiet -print_format xml -select_streams v:0 -show_format -show_streams "rtsp://ipcam:8554/main"
> ffprobe -v quiet "rtsp://ipcam:8554/main"
> ffprobe -v quiet -print_format xml "rtsp://ipcam:8554/main"  
```

**Comment by sri-wahyuni10** [comment]
when i run the code, i have the output this 
<img width="692" alt="image" src="https://github.com/chenxinfeng4/ffmpegcv/assets/66435634/b0ea23f2-e5db-4751-8fed-6544f6a45867">

i using google colab for run my code.

**Comment by chenxinfeng4** [comment]
Can you run the code one by one? Or could you share me your colab environment link?

**Comment by chenxinfeng4** [comment]
There's no bug in my test platform (Ubuntu server + windows client).
Create a RTSP stream.
```bash
# [Server 10.50.7.95] create a rtsp server
docker run --rm -it -e MTX_PROTOCOLS=tcp -p 8554:8554 -p 1935:1935 -p 8888:8888 -p 8889:8889 bluenviron/mediamtx
# [Server 10.50.7.95] create a stream 
ffmpeg -re -stream_loop -1 -i TEST_VIDEO.mp4 -c copy -f rtsp rtsp://localhost:8554/mystream

# [Client] pull a stream
ffplay rtsp://10.50.7.95:8554/mystream
ffprobe -v quiet -print_format xml -select_streams v:0 -show_format -show_streams "rtsp://10.50.7.95:8554/mystream"
```

Client ffmpegcv
```python
vid = ffmpegcv.VideoCaptureStream("rtsp://10.50.7.95:8554/mystream")
ret, image = vid.read()
```
![image](https://github.com/chenxinfeng4/ffmpegcv/assets/17546446/3f3fc84f-a35a-4c85-9200-dbf994169420)

Please check your platform

**Comment by chenxinfeng4** [comment]
I've test the code in `RTSP` and `RTMP`, but could not repeat the bug. Maybe `"rtsp://ipcam:8554/main"` is not well established in your case.

**Comment by chenxinfeng4** [comment]
I cann't access "rtsp://ipcam:8554/main" in my network. And colab seems OK to access remote stream. 
> !ffprobe http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear2/prog_index.m3u8

I think that's a network issue of your "rtsp://ipcam:8554/main".

**Comment by sri-wahyuni10** [comment]
Thanks a lot,  i will try to check my link rtsp.

**Comment by chenxinfeng4** [comment]
You can use my test stream.
```python
vid = ffmpegcv.VideoCaptureStream('rtsp://chenxinfeng.com:8554/stream400x300_mpeg4', pix_fmt='rgb24')
for _ in range(20): 
  #Start frames may have mosaic noise from network
  vid.read()
ret, frame = vid.read()
vid.release()
plt.imshow(frame)
```
