### ISSUE TITLE
Modification on line 55 in ffmpeg_reader_camera.py

### ISSUE THREAD

**Issue by brodwix** [chenxinfeng4/ffmpegcv#17]
Hello, thank you so much for your contribution.
I was running the following code shown in the documentation:

`from ffmpegcv.ffmpeg_reader_camera import query_camera_options`
`options = query_camera_options(0)  # or query_camera_options("Integrated Camera") `
`print(options)`

i got AssertionError on line 59 in _query_camera_divices_win:
`assert len(matches) == len(alternative_names)`

I modified line 55 in order to get the first matches. It was a regex problem:

from this:
`pattern = re.compile(r'\[[^\]]*?\]  "([^"]*)"')`

to this:
`pattern = re.compile(r'"([^"]*)" ')`

i ran the code again and now it works as expected.

Is it possible if you modify this expression in your source code?

line 55 in ffmpeg_reader_camera.py

Thanks in advance

Bruno

**Comment by chenxinfeng4** [comment]
can you show me the string of `dshowliststr` in line 53?

**Comment by brodwix** [comment]
Here's my string of `dshowliststr` :

`'[dshow @ 00000253ae97d3c0] "Integrated Camera" (video)\r\n[dshow @ 00000253ae97d3c0]   Alternative name "@device_pnp_\\\\?\\usb#vid_5986&pid_212a&mi_00#6&7b9e12d&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\\global"\r\n[dshow @ 00000253ae97d3c0] "OBS Virtual Camera" (video)\r\n[dshow @ 00000253ae97d3c0]   Alternative name "@device_sw_{860BB310-5D01-11D0-BD3B-00A0C911CE86}\\{A3FCE0F5-3493-419F-958A-ABA1250EC20B}"\r\n[dshow @ 00000253ae97d3c0] "Microphone Array (Intel® Smart Sound Technology for Digital Microphones)" (audio)\r\n[dshow @ 00000253ae97d3c0]   Alternative name "@device_cm_{33D9A762-90C8-11D0-BD43-00A0C911CE86}\\wave_{D511426D-AFF7-4290-9D47-2A85A7C3B3C1}"\r\n[in#0 @ 00000253ae967480] Error opening input: Immediate exit requested\r\n'`

**Comment by chenxinfeng4** [comment]
Try this to see if it works for you. I'll release this version after testing in days.

```
pip install -U git+https://github.com/chenxinfeng4/ffmpegcv
```
