### ISSUE TITLE
Request: RTSP routes

### ISSUE THREAD

**Issue by fonchii** [chenxinfeng4/ffmpegcv#2]
first of all, great job!, I wanted to ask if it is possible to add the option to get frames from an rtsp route, something like 
'rtsp://admin:admin@ip_cam/'

**Comment by chenxinfeng4** [comment]
It's feasible for ffmpeg, but not for ffmpegcv.  The ffmpegcv is specific designed for ROI operations in local video sources. If you want to connect RTSP source, please try the original ffmpeg or adapt ffmpegcv code like below `https://github.com/chenxinfeng4/ffmpegcv/tree/main/ffmpegcv/ffmpeg_reader_camera.py`

**Comment by chenxinfeng4** [comment]
I've updated the RTSP reading in latest version. This feature is experimental. You can try it.
