### ISSUE TITLE
Does "ffmpegcv.VideoCaptureStream"  support GPU decoding?

### ISSUE THREAD

**Issue by junkai1992** [chenxinfeng4/ffmpegcv#23]
Does "ffmpegcv.VideoCaptureStream"  support GPU decoding?

**Comment by chenxinfeng4** [comment]
The "ffmpegcv.VideoCaptureStream" didn't support GPU decoding yet.

The `Stream` may be `mjpeg`, `mpeg` or `h264/h265`. However, only `h264/h265` is supported by NVIDIA GPU decoding. For the sake of compatibility, the experimental `ffmpegcv.VideoCaptureStream` only use CPU version.

However, it's possible to create a `ffmpegcv.VideoCaptureStreamNV`  to support GPU. Just reference to the `VideoCaptureNV`. You can try it.

```python
print(vid_videoCap_cpu.ffmpeg_cmd)
print(vid_videoCap_gpu.ffmpeg_cmd)
print(vid_streamCap_cpu.ffmpeg_cmd)
# guess how vid_streamCap_gpu.ffmpeg_cmd
```
