### ISSUE TITLE
How to minimize the buffer of VideoCaptureStream?

### ISSUE THREAD

**Issue by tienshawn** [chenxinfeng4/ffmpegcv#24]
How to reduce the buffer of VideoCaptureStream as little as possible? 
For some purpose, when the VideoCaptureStream starts receiving the frame, I want it to send immediately that frame to the data process instead of buffering. 
How to achieve that with ffmpegcv? And is there a way to do it with OpenCV?

**Comment by chenxinfeng4** [comment]
I think your question is how to view the Stream in real time way. Set the latency as low as possible.
1. Try to reduce the buffer size
![图片](https://github.com/chenxinfeng4/ffmpegcv/assets/17546446/5f381170-3de8-4cb7-820b-c8bb4acd489a)

2. Or try the experimental code. I'm testing that code. The code may have issues, please try to figure it out. I won't release the code at this moment. 
> ffmpegcv/ffmpeg_reader_stream_realtime.py

It's the opencv code to open a stream.
```
import cv2
import os

RTSP_URL = 'rtsp://user:pass@192.168.0.189:554/h264Preview_01_main'

os.environ['OPENCV_FFMPEG_CAPTURE_OPTIONS'] = 'rtsp_transport;udp'

cap = cv2.VideoCapture(RTSP_URL, cv2.CAP_FFMPEG)

if not cap.isOpened():
    print('Cannot open RTSP stream')
    exit(-1)

while True:
    _, frame = cap.read()
    cv2.imshow('RTSP stream', frame)

    if cv2.waitKey(1) == 27:
        break

cap.release()
cv2.destroyAllWindows()
```

**Comment by tienshawn** [comment]
Thank, gonna try it out!
