### ISSUE TITLE
VideoCapture crop

### ISSUE THREAD

**Issue by uptotec** [chenxinfeng4/ffmpegcv#25]
HI
when I use VideoCapture with crop and gray pixel format the beginning for each frames gets added to the end of the last frame so the frames gets exported as show in this image.
![image](https://github.com/chenxinfeng4/ffmpegcv/assets/38630967/a0462a38-b532-49a6-a0f3-072ba49e5885)
here is the code that exported these frames
```python
from ffmpegcv import VideoCapture
import cv2

cap = VideoCapture('test2.mp4', pix_fmt='gray',
                   crop_xywh=(332, 57, 84, 35))

frameCounter = 0

while frameCounter < ((23*60+14)-(2*60+23)) * 60:
    frameCounter += 1
    try:
        ret, frame = cap.read()
        if not ret:
            break
    except:
        break

    if frameCounter % 60 != 0:
        continue

    cv2.imwrite('out/frame'+str(frameCounter)+'.jpg', frame)
    frameCounter += 1
    pass
cap.release()

cap.release()
```

**Comment by chenxinfeng4** [comment]
I didn't get your question. Could you specify your issue? 

Suggestion for the code `crop_xywh=(332, 57, 84, 35)`. You are supposed to use even number of `W,H` in video encoding&decoding. Please try  `crop_xywh=(332, 57, 84, 36)` even if the `35` may works for you.

**Comment by uptotec** [comment]
ok that fixed the problem thanks for the fast reply

**Comment by uptotec** [comment]
can I ask why only even numbers work ?

**Comment by chenxinfeng4** [comment]
The video is store as YUV420 mostly. YUV420 means that the U and V channels have **half** the resolution of the luma (Y) channel. So, it's better to use even number. Some video encoders must use even number, some are not.
