### ISSUE TITLE
How to index frame

### ISSUE THREAD

**Issue by sarkadava** [chenxinfeng4/ffmpegcv#27]
Hey, 
is there a way how to index certain frame range with ffmpegcv? Something like this (in opencv):

for fra in frames:
    capture.set(cv2.CAP_PROP_POS_FRAMES, fra) ##THIS SPECIFICALLY
    ret, frame = capture.read()
    if ret:
        #cv2.imshow('frame',frame)
        #cv2.waitKey(1000)
        out.write(frame)
        # display th loading image with im.show() to see if the frames are loaded correctly
if not ret:
            #         print('a frame was dropped: ' + str(fra)) 
    capture.release()
        # out.release()

Thank you!

**Comment by chenxinfeng4** [comment]
you can try openmmlab/mmcv



---- Replied Message ----
| From | Šárka ***@***.***> |
| Date | 09/27/2023 04:05 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [chenxinfeng4/ffmpegcv] How to index frame (Issue #27) |

Hey,
is there a way how to index certain frame range with ffmpegcv? Something like this (in opencv):

for fra in frames:
capture.set(cv2.CAP_PROP_POS_FRAMES, fra) ##THIS SPECIFICALLY
ret, frame = capture.read()
if ret:
#cv2.imshow('frame',frame)
#cv2.waitKey(1000)
out.write(frame)
# display th loading image with im.show() to see if the frames are loaded correctly
if not ret:
# print('a frame was dropped: ' + str(fra))

capture.release()
    # out.release()


Thank you!
