### ISSUE TITLE
ffmpegcv is not running.

### ISSUE THREAD

**Issue by MonteiroAlvesMatheus** [chenxinfeng4/ffmpegcv#29]
Following the tutorial on PyPI to install ffmpegcv, I did as instructed, but it still doesn't work. The images below show ffmpeg 6.0.1 installed, ffmpegcv installed, and finally, an image showing an error when I try to run video capture and then save the video capture.

![image](https://github.com/chenxinfeng4/ffmpegcv/assets/106630689/9db02cd9-8643-4eed-9e70-223b3ff8489f)

![image](https://github.com/chenxinfeng4/ffmpegcv/assets/106630689/ce45ece2-8178-4a5a-aaee-459ffe80af44)

![image](https://github.com/chenxinfeng4/ffmpegcv/assets/106630689/2183a859-5e21-4b82-817d-c1e02f7b93e8)

how to solve this issue?

**Comment by chenxinfeng4** [comment]
Can you print the result below?
```
import shutil
shutil.which("ffmpeg")
shutil.which("ffprobe")
```

**Comment by chenxinfeng4** [comment]
How about this?
```python
def _check():
    if not shutil.which("ffmpeg") or not shutil.which("ffprobe"):
        raise RuntimeError(
            "The ffmpeg is not installed. \n\n"
            "Please install ffmpeg via:\n    "
            "conda install ffmpeg"
        )


_check()
```

**Comment by chenxinfeng4** [comment]
did  your use `conda activate tracker` ?

**Comment by chenxinfeng4** [comment]
Since no more comments, the issue was closed.
