### ISSUE TITLE
Read by frame id

### ISSUE THREAD

**Issue by Ilyabasharov** [chenxinfeng4/ffmpegcv#3]
Great work! Do u plan to support reading frames by indexes (random access) ?

**Comment by chenxinfeng4** [comment]
Yeah, I do really need "read frame by indexes" for my own project. However, I find it's very hard or would be low efficient. 

If you tool, **I recommand you** to `openmmlab/mmcv`.  The `mmcv` will work great in most codecs. **But be careful that `mmcv` sometimes will read wrong frame index** without warning -- may be the unknown compatibility bug between the open-cv and video codec.
```python
import mmcv
video = mmcv.VideoReader('test.mp4')
# read a frame by index
img = video[100]

# read some frames
img = video[5:10]
```

**Comment by Ilyabasharov** [comment]
thanks! btw I have found good library which supports gpu random access video reading, but I have also faced with this issue. sometimes this lib will read similar frames. so in the end im using opencv. Thanks for mmcv suggestion, I will try!
