### ISSUE TITLE
Benchmark vs NVidia VPF/PyNvCodec

### ISSUE THREAD

**Issue by thejasonfisher** [chenxinfeng4/ffmpegcv#33]
This is more of a TODO for someone, possibly myself .. looking to see the performance of reading a stream into a GPU surface vs the NVidia VPF option, which I think also uses FFMPEG pipe?

https://github.com/NVIDIA/VideoProcessingFramework

**Comment by chenxinfeng4** [comment]
The NVIDIA/VideoProcessingFramework is a really great project. It can convert pixel format from raw NV12 -> RGB(HWC) -> CHW all in GPU, and that's the feature I'm always searching to link video reading with DeepLearning Models inference.

Currently, the ffmpegcv is definitely slower than VPF. 
- The ffmpegcv recruits pixel format convertion in CPU
- The ffmpegcv will always copy image data GPU(device) ==> CPU(host).

> VPF ... which I think also uses FFMPEG pipe?

The VPF can keep image data in GPU without pipe back.

But VPF didn't support as much API as the ffmpeg(cv)
- lacked camera/stream reading
- lacked crop/pad ROI operations. 
- compatibility with ffmpeg options?

---
I'll create a new project to make ffmpegcv taking advantage of VPF.  That's a long time in the future. Thank you for your interests in ffmpegcv.

**Comment by thejasonfisher** [comment]
Understood, and thank you for your contribution to the community here.

I currently have the VPF for Deep Learning + CUDA + GL side.  I am interested in seeing if ffmpeg can be used for other source input formats, even if only as a pipe that has no decoding.  (I am using SurfacePtr into CUDA/PyTorch/GL/etc -- GPU-only pipeline)

**Comment by chenxinfeng4** [comment]
Well, I fail to set up the VPF environment. Fail in the very first step. I try many times, 1 local ubuntu machine, 2 docker. 

1. The VPF destroyed the ubuntu enviroment, it tried to update my GPU driver and base cuda version without warning me. It destoryed all my deeplearning applications.
2. The official docker didn't work at all. It's not a simple open-box-run installation guide. I must mannual type many commands, but still fail. 
```
root@711d85649cfa:/# apt-get install -y cuda
Unpacking nvidia-utils-550 (550.54.14-0ubuntu1) ...
dpkg: error processing archive /tmp/apt-dpkg-install-xJ1NjX/6-nvidia-utils-550_550.54.14-0ubuntu1_amd64.deb (--unpack):
 unable to make backup link of './usr/bin/nvidia-debugdump' before installing new version: Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../7-libnvidia-cfg1-550_550.54.14-0ubuntu1_amd64.deb ...
Unpacking libnvidia-cfg1-550:amd64 (550.54.14-0ubuntu1) ...
dpkg: error processing archive /tmp/apt-dpkg-install-xJ1NjX/7-libnvidia-cfg1-550_550.54.14-0ubuntu1_amd64.deb (--unpack):
 unable to make backup link of './usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.550.54.14' before installing new version: Invalid cross-device link
Errors were encountered while processing:
 /tmp/apt-dpkg-install-xJ1NjX/0-libnvidia-compute-550_550.54.14-0ubuntu1_amd64.deb
 /tmp/apt-dpkg-install-xJ1NjX/1-nvidia-firmware-550-550.54.14_550.54.14-0ubuntu1_amd64.deb
 /tmp/apt-dpkg-install-xJ1NjX/2-libnvidia-extra-550_550.54.14-0ubuntu1_amd64.deb
 /tmp/apt-dpkg-install-xJ1NjX/3-nvidia-compute-utils-550_550.54.14-0ubuntu1_amd64.deb
 /tmp/apt-dpkg-install-xJ1NjX/4-libnvidia-decode-550_550.54.14-0ubuntu1_amd64.deb
 /tmp/apt-dpkg-install-xJ1NjX/5-libnvidia-encode-550_550.54.14-0ubuntu1_amd64.deb
 /tmp/apt-dpkg-install-xJ1NjX/6-nvidia-utils-550_550.54.14-0ubuntu1_amd64.deb
 /tmp/apt-dpkg-install-xJ1NjX/7-libnvidia-cfg1-550_550.54.14-0ubuntu1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

The VPF is heavy and not friendly, I love ffmpeg.

**Comment by chenxinfeng4** [comment]
try  latest ffmepgcv, I enforce cuda to do pix_fmt rgb24 and chw tensor format. the new function is called "toCUDA".
