### ISSUE TITLE
VideoCaptureStream和nv是可以一起的

### ISSUE THREAD

**Issue by zylo117** [chenxinfeng4/ffmpegcv#37]
nv是可以对rtsp硬解

**Comment by chenxinfeng4** [comment]
我知道，但是性能没有多大提升，所以也没有用

**Comment by chenxinfeng4** [comment]
可以设置 codec = h264_cuvid, 或者 hevc_cuvid, 手动开启nv的硬解。

**Comment by zylo117** [comment]
主要是合并在一起，就可以精简一个多余的类，更接近opencv的实现

**Comment by zylo117** [comment]
VideoCaptureStream也没有codec的参数啊

**Comment by chenxinfeng4** [comment]
有codec 的参数
```
In [2]: ffmpegcv.VideoCaptureStream
Out[2]: <function ffmpegcv.VideoCaptureStream(stream_url, codec=None, pix_fmt='bgr24', crop_xywh=None, resize=None, resize_keepratio=True, resize_keepratioalign='center')>
```

**Comment by zylo117** [comment]
哦哦看到了，pip直接安装的版本是没有的

**Comment by chenxinfeng4** [comment]
不应该呀，pip 是与 github 同步更新的。

想听听作为你用户的反馈，
1. 你用ffmpegcv 主要用作什么功能？什么场景
2. 为什么用 ffmpegcv ，或者什么时候用 ffmpegcv ，什时候用 opencv？

**Comment by zylo117** [comment]
pip的版本的steam类真没有codec。我是用来解码视频跑ai的。opencv是好用，但是关于视频图片解码编码，总是怕这个那个专利，迟迟不跟进，说是支持硬件编解码其实是不完全支持，用起来真恶心。我之前也用过其他ffmpeg的python subprocess封装体，确实没有你这个好用。不过你这个在视频源个别异常的错误信息好像没有打印出来，而且subprocess有时候是会因为程序卡住而卡住的，这种情况要加timeout，打log，不然用户都不知道干嘛卡在哪里卡了

**Comment by chenxinfeng4** [comment]
我也是为了 视频跑AI，才开发 ffmpegcv。opencv 带cuda的编译太麻烦，我也是外行。NVIDIA 的VPF 性能比我这个好，但是更难安装，庞大，难装 还搞崩我的环境。ffmpegcv 是一个中间地带，简单快捷性能折中，相当于一种语法糖。

subprocess 的确是个问题，ffmpeg报错的自由度太大，没法预期。改进报错信息提示 太复杂，收益低，你感兴趣有能力可以提交 PR。我平时debug，是通过print( vid.ffmpeg_cmd ).

**Comment by zylo117** [comment]
原来是同行。是的，带cuda的我都害怕，太庞大，大项目编译又难通过。ffmpeg就挺好的

**Comment by chenxinfeng4** [comment]
> 原来是同行。是的，带cuda的我都害怕，太庞大，大项目编译又难通过。ffmpeg就挺好的

快尝试ffmpegcv最新的功能，整合了cuda。比原先的 rbg24 版本快2倍，CPU占用率少节省一半以上。在有NVCC编译器环境中就能使用，安装很方便。
```python
cap = ffmpegcv.toCUDA(
    ffmpegcv.VideoCaptureNV(file, pix_fmt='nv12', resize=(W,H)),
    tensor_format='CHW')

for frame_CHW_cuda in cap:
    frame_CHW_cuda = (frame_CHW_cuda - mean) / std
    result = model(frame_CHW_cuda)
```

**Comment by zylo117** [comment]
> > 原来是同行。是的，带cuda的我都害怕，太庞大，大项目编译又难通过。ffmpeg就挺好的
> 
> 快尝试ffmpegcv最新的功能，整合了cuda。比原先的 rbg24 版本快2倍，CPU占用率少节省一半以上。在有NVCC编译器环境中就能使用，安装很方便。
> 
> ```python
> cap = ffmpegcv.toCUDA(
>     ffmpegcv.VideoCaptureNV(file, pix_fmt='nv12', resize=(W,H)),
>     tensor_format='CHW')
> 
> for frame_CHW_cuda in cap:
>     frame_CHW_cuda = (frame_CHW_cuda - mean) / std
>     result = model(frame_CHW_cuda)
> ```

好啊，很有趣的实现，解码的帧直接接入模型确实可以省不少资源
