### ISSUE TITLE
support async

### ISSUE THREAD

**Issue by sugizo** [chenxinfeng4/ffmpegcv#40]
nice to support async ?

the ffmpeg parameter can be run using another python ffmpeg module 
**e.g. module**
```
typed-ffmpeg 
ffmpeg-python
```

**e.g. code**
```
import ffmpeg
url = 'http://takemotopiano.aa1.netvolante.jp:8190/nphMotionJpeg?Resolution=320x240&Quality=Standard&Framerate=30'
output = 'rtsp_%Y_%m_%d_%H_%M_%S.mp4'
scale = 'scale = 320 : -1'
segment_time = '00:01:00' 

stream = ffmpeg.input(url).output(filename = output, 
                                  vcodec = 'libx264', #acodec = 'copy', 
                                  reset_timestamps = 1, 
                                  strftime = 1, 
                                  f = 'segment', 
                                  segment_time = segment_time, 
                                  segment_atclocktime = 1, 
                                  vf = scale, 
                                  r = 25, ).overwrite_output().run_async()
```

**to stop async**
`stream.terminate()`

best regards

**Comment by chenxinfeng4** [comment]
What kind of case you like to use the async? For the video transcoding? It's not a good ideal to use ffmpegcv to do video transcode.

**Comment by sugizo** [comment]
> What kind of case you like to use the async? For the video transcoding? 

**objective**
create video continously 
from rtsp camera 
with duration that defined 
in segment_time parameter

**Comment by chenxinfeng4** [comment]
If you just want the transcoding or segment, you'd better use the `ffmpeg`. The ffmpegcv behaves similiar to opencv, it will read frame by frame to numpy in foreground, and hence leads to additional cost. Otherwise, you can manually program by multiprocessing.
