### ISSUE TITLE
对release和isOpened函数存在一些疑问

### ISSUE THREAD

**Issue by Pengtap** [chenxinfeng4/ffmpegcv#41]
1. 您好，我进行并行处理多视频流时（使用的是VideoCaptureStream；循环条件是判断isOpened返回值是否为True），发现运行一段时间后__isopen会自动变为False，这是为啥呀？

- 例如：

cap=ffmpegcv.VideoCaptureStream(url)
while cap.isOpened():
   //运行一段时间后isOpened()会返回False
   pass

2. 另外，自建了一个处理视频流得对象，在初始化阶段通过VideoCaptureStream获取帧的尺寸信息，并在运行独立的进程获取、处理帧。在运行独立进程前release获取尺寸信息的capture是正常的，但是在运行独立进程后release就会卡住，这是为啥啊？

- 例如：

cap=ffmpegcv.VideoCaptureStream(url)
shape = cap.out_numpy_shape
// cap.release()      //这时是正常的
Process(target="child_prc"， args=(url, shape))
// cap.release()      // 这时会直接卡住

**Comment by chenxinfeng4** [comment]
1.  你说的 isOpened() 会变成 False, 可能的情况是你的流出现问题，frame 返回 None 值。

- 检查你的网络是否通畅。
- 看看你数据的后处理速度是否跟得上 视频流的速度，不要有积压的frame（不要欠债）。欠债太多会崩溃
- 建议你尝试
```python
# 保持网络通畅
cap = ffmpegcv.ReadLiveLast(ffmpegcv.VideoCaptureStreamRT, stream_url) #这个丢弃过往帧，不会‘欠债’
cap = ffmpegcv.ReadLiveLast(ffmpegcv.VideoCaptureStream, stream_url) #可能也差不多一样
```

```python
# 出现问题溯源 VideoCaptureStream
    def read_(self):
        for i in range(self.step):
            in_bytes = self.process.stdout.read(np.prod(self.out_numpy_shape))
        if not in_bytes:
            self.release()
            return False, None

        self.iframe += 1
        img = None
        img = np.frombuffer(in_bytes, np.uint8).reshape(self.out_numpy_shape)
        return True, img

    def read(self):
        ret, img = self.q.get()
        return ret, img

    def isOpened(self):
        return self._isopen
```

**Comment by chenxinfeng4** [comment]
2. 你对python多进程的理解有问题。有一些变量/对象 是无法通过多线程共享的。所以你想在子进程用 cap, 在主进程释放cap，这个原理是不通的。
- ffmpegcv 有一个 noblock 的函数，可以把编码、解码发送到后台(多进程) 运行。你可以看里面是怎么创建和使用多进程的，使用共享数据。希望能作为你项目的参考。

**Comment by Pengtap** [comment]
> 2. 你对python多进程的理解有问题。有一些变量/对象 是无法通过多线程共享的。所以你想在子进程用 cap, 在主进程释放cap，这个原理是不通的。
> 
> * ffmpegcv 有一个 noblock 的函数，可以把编码、解码发送到后台(多进程) 运行。你可以看里面是怎么创建和使用多进程的，使用共享数据。希望能作为你项目的参考。

您好，您理解错我的意思了，我是在主进程中创建了个cap获取帧的信息，并单独运行一个进程来重新创建一个新的cap来完成取帧操作（python不是有线程锁吗？就搞了单独的进程来完成取帧），两个cap是相互独立的，但会出现上述问题。

**Comment by chenxinfeng4** [comment]
能否贴一些你详细的代码，我测试看看？

**Comment by Pengtap** [comment]
> 能否贴一些你详细的代码，我测试看看？

好的，我对我的代码进行了一定的精简。


    import ffmpegcv
    from multiprocessing import Process, Array

    class VP:
        def __init__(self, camera_id):
            cap = ffmpegcv.VideoCaptureStream(camera_id)
            self.img_height, self.img_width, _ = cap.out_numpy_shape
            self.out_numpy_shape = (self.img_height, self.img_width, 3)
            cap.release()
            self.shared_array = Array('b', int(np.prod(self.out_numpy_shape)))
            self.process = Process(target=self.child_process, args=(self.shared_array, camera_id), daemon=True)
            self.process.start()
            # cap.release() # 在这里时会阻塞

        def get_frame(self):
            return np.frombuffer(self.shared_array.get_obj(), dtype=np.uint8).reshape(*self.out_numpy_shape)[:, :, :]

        @staticmethod
        def child_process(shared_array, camera_id):
            cap = None
            try:
                cap = ffmpegcv.ReadLiveLast(ffmpegcv.VideoCaptureStream, camera_id)
                h, w, _ = cap.out_numpy_shape

                n = 0
                t0 = time.time()
                while True:
                    n += 1
                    if n >= 25:
                        ret, frame = cap.read()
                        if not ret:
                            cap = ffmpegcv.ReadLiveLast(ffmpegcv.VideoCaptureStream, camera_id)
                        else:
                            np_array = np.frombuffer(shared_array.get_obj(), dtype=np.uint8).reshape(cap.out_numpy_shape)
                            np_array[:, :, :] = frame
                        n = 0
                    t1 = time.time()
                    time.sleep(max((0.04 - (t1 - t0)), 0))
                    t0 = time.time()
            except Exception as e:
                print(f"视频流出错： {e}")
            finally:
                if cap is not None:
                    cap.release()

**Comment by chenxinfeng4** [comment]
这个代码你是怎么使用的，怎么创建实例，什么时候读取、释放？能再补充一下吗？

**Comment by Pengtap** [comment]
项目比较大，只能给您部分较为简单的执行代码，请见谅
            video = VP(url)
            time.sleep(0.04)
            t0 = time.time()
            while  Ture:
                img = video.get_frame().copy()
                sm = np.sum(img[:, :, 0]) - img.size / 3
                if sm == 0:
                    lprint(f"{self.uniqueID} 跳过本次预测。。。")
                else:
                    # 一些操作
                t1 = time.time()
                time.sleep(max(self.interval - (t1 - t0), 0))
                t0 = time.time()

**Comment by chenxinfeng4** [comment]
目前看来，你的代码潜在问题很大：
1. cap 的释放？你应该是在子进程释放，但是child_process里面没有 release 相关代码。
```python
class VP:
    def __init__(self, camera_id):
        cap = ffmpegcv.VideoCaptureStream(camera_id)
        self.img_height, self.img_width, _ = cap.out_numpy_shape
        self.out_numpy_shape = (self.img_height, self.img_width, 3)
        cap.release()
        self.shared_array = Array('b', int(np.prod(self.out_numpy_shape)))
        self.process = Process(target=self.child_process, args=(self.shared_array, camera_id), daemon=True)
        self.process.start()
        # cap.release() # 在这里时会阻塞 === 这里release 的是VP里面的cap，而不是子进程的cap
```

2. 共享 array 的保护. 没有加锁。读和写可能同时发生：刚写到一半，就被另一个进程被读出来，导致读取的画面撕裂。这个问题我遇到过，我在 ffmpeg_noblock.py 里面 通过lock或者queue，最后才解决的。
```python
np.frombuffer(self.shared_array.get_obj(), dtype=np.uint8).reshape(*self.out_numpy_shape)[:, :, :]
...
np_array[:, :, :] = frame
```

**Comment by chenxinfeng4** [comment]
> 项目比较大，只能给您部分较为简单的执行代码，请见谅 video = VP(url) time.sleep(0.04) t0 = time.time() while Ture: img = video.get_frame().copy() sm = np.sum(img[:, :, 0]) - img.size / 3 if sm == 0: lprint(f"{self.uniqueID} 跳过本次预测。。。") else: # 一些操作 t1 = time.time() time.sleep(max(self.interval - (t1 - t0), 0)) t0 = time.time()

麻烦格式化一下代码，方便复现你的问题

**Comment by Pengtap** [comment]
video = VP(url)
    time.sleep(0.04)
    t0 = time.time()
    while Ture:
        img = video.get_frame().copy()
    sm = np.sum(img[:, :, 0]) - img.size / 3
    if sm == 0:
        lprint(f"{self.uniqueID} 跳过本次预测。。。")
    else:
    # 一些操作
    t1 = time.time()
    time.sleep(max(self.interval - (t1 - t0), 0))
    t0 = time.time()

**Comment by Pengtap** [comment]
> 目前看来，你的代码潜在问题很大：
> 
> 1. cap 的释放？你应该是在子进程释放，但是child_process里面没有 release 相关代码。
> 
> ```python
> class VP:
>     def __init__(self, camera_id):
>         cap = ffmpegcv.VideoCaptureStream(camera_id)
>         self.img_height, self.img_width, _ = cap.out_numpy_shape
>         self.out_numpy_shape = (self.img_height, self.img_width, 3)
>         cap.release()
>         self.shared_array = Array('b', int(np.prod(self.out_numpy_shape)))
>         self.process = Process(target=self.child_process, args=(self.shared_array, camera_id), daemon=True)
>         self.process.start()
>         # cap.release() # 在这里时会阻塞 === 这里release 的是VP里面的cap，而不是子进程的cap
> ```
> 
> 2. 共享 array 的保护. 没有加锁。读和写可能同时发生：刚写到一半，就被另一个进程被读出来，导致读取的画面撕裂。这个问题我遇到过，我在 ffmpeg_noblock.py 里面 通过lock或者queue，最后才解决的。
> 
> ```python
> np.frombuffer(self.shared_array.get_obj(), dtype=np.uint8).reshape(*self.out_numpy_shape)[:, :, :]
> ...
> np_array[:, :, :] = frame
> ```

1、对于release，我在finally中已经写了
2、lock等细节优化部分全部省略了

**Comment by chenxinfeng4** [comment]
这个函数也很大问题。返回的np.array 会试试被子进程修改哟，是个动态的。你最好clone一下。或者你最好就使用我原生的 noblock, ReadLiveLast 组合一下。
    def get_frame(self):
        return np.frombuffer(self.shared_array.get_obj(), dtype=np.uint8).reshape(*self.out_numpy_shape)[:, :, :]

**Comment by Pengtap** [comment]
> 这个函数也很大问题。返回的np.array 会试试被子进程修改哟，是个动态的。你最好clone一下。或者你最好就使用我原生的 noblock, ReadLiveLast 组合一下。 def get_frame(self): return np.frombuffer(self.shared_array.get_obj(), dtype=np.uint8).reshape(*self.out_numpy_shape)[:, :, :]

嗯嗯，这个copy等优化操作也省略了

**Comment by chenxinfeng4** [comment]
> ```
> video = VP(url)
> time.sleep(0.04)
> t0 = time.time()
> while Ture:
>     img = video.get_frame().copy()
> sm = np.sum(img[:, :, 0]) - img.size / 3
> if sm == 0:
>     lprint(f"{self.uniqueID} 跳过本次预测。。。")
> else:
> # 一些操作
> t1 = time.time()
> time.sleep(max(self.interval - (t1 - t0), 0))
> t0 = time.time()
> ```

哪里会有问题，运行哪的时候会卡住？

**Comment by Pengtap** [comment]
> > ```
> > video = VP(url)
> > time.sleep(0.04)
> > t0 = time.time()
> > while Ture:
> >     img = video.get_frame().copy()
> > sm = np.sum(img[:, :, 0]) - img.size / 3
> > if sm == 0:
> >     lprint(f"{self.uniqueID} 跳过本次预测。。。")
> > else:
> > # 一些操作
> > t1 = time.time()
> > time.sleep(max(self.interval - (t1 - t0), 0))
> > t0 = time.time()
> > ```
> 
> 哪里会有问题，运行哪的时候会卡住？

初始化的release那

**Comment by chenxinfeng4** [comment]
```
import ffmpegcv
from multiprocessing import Process, Array
import time
import numpy as np


class VP:
    def __init__(self, camera_id):
        cap = ffmpegcv.VideoCaptureStream(camera_id)
        self.img_height, self.img_width, _ = cap.out_numpy_shape
        self.out_numpy_shape = (self.img_height, self.img_width, 3)
        cap.release()
        self.shared_array = Array('b', int(np.prod(self.out_numpy_shape)))
        self.process = Process(target=self.child_process, args=(self.shared_array, camera_id), daemon=True)
        self.process.start()
        cap.release() # 在这里时会阻塞

    def get_frame(self):
        return np.frombuffer(self.shared_array.get_obj(), dtype=np.uint8).reshape(*self.out_numpy_shape)[:, :, :]

    @staticmethod
    def child_process(shared_array, camera_id):
        cap = None
        try:
            cap = ffmpegcv.ReadLiveLast(ffmpegcv.VideoCaptureStream, camera_id)
            h, w, _ = cap.out_numpy_shape

            n = 0
            t0 = time.time()
            while True:
                n += 1
                if n >= 25:
                    ret, frame = cap.read()
                    if not ret:
                        cap = ffmpegcv.ReadLiveLast(ffmpegcv.VideoCaptureStream, camera_id)
                    else:
                        np_array = np.frombuffer(shared_array.get_obj(), dtype=np.uint8).reshape(cap.out_numpy_shape)
                        np_array[:, :, :] = frame
                    n = 0
                t1 = time.time()
                time.sleep(max((0.04 - (t1 - t0)), 0))
                t0 = time.time()
        except Exception as e:
            print(f"视频流出错： {e}")
        finally:
            if cap is not None:
                cap.release()

video = VP(url)
time.sleep(0.04)
t0 = time.time()
for i in range(1000):
    img = video.get_frame().copy()
sm = np.sum(img[:, :, 0]) - img.size / 3
interval = 0.2
if sm == 0:
    print(f" 跳过本次预测。。。")
else:
    pass
# 一些操作
t1 = time.time()
time.sleep(max(interval - (t1 - t0), 0))
t0 = time.time()
```
这个代码，并没有卡顿。你可以尝试先升级 ffmpegcv。有些bug可能在最新版本里面被修复了。
> pip install -U git+https://github.com/chenxinfeng4/ffmpegcv

**Comment by Pengtap** [comment]
> class VP:
>     def __init__(self, camera_id):
>         cap = ffmpegcv.VideoCaptureStream(camera_id)
>         self.img_height, self.img_width, _ = cap.out_numpy_shape
>         self.out_numpy_shape = (self.img_height, self.img_width, 3)
>         cap.release()
>         self.shared_array = Array('b', int(np.prod(self.out_numpy_shape)))
>         self.process = Process(target=self.child_process, args=(self.shared_array, camera_id), daemon=True)
>         self.process.start()
>         cap.release() # 在这里时会阻塞

好的，我去试试。
另外，好像初始化里第一个release没关掉欸。

    class VP:
       def __init__(self, camera_id):
           cap = ffmpegcv.VideoCaptureStream(camera_id)
           self.img_height, self.img_width, _ = cap.out_numpy_shape
           self.out_numpy_shape = (self.img_height, self.img_width, 3)
           # cap.release() # 这里没关掉
           self.shared_array = Array('b', int(np.prod(self.out_numpy_shape)))
           self.process = Process(target=self.child_process, args=(self.shared_array, camera_id), daemon=True)
           self.process.start()
           cap.release() # 在这里时会阻塞

**Comment by chenxinfeng4** [comment]
Python
```python
video = VP(url) #VP里面cap哪里释放都行，释放多少次都行
...
```

查看 后台进程
```bash
root@DESKTOP-J4QJ7ON:~# ps aux | grep ffmpeg
root      220342  4.1  0.9 1576164 79720 pts/5   SLl+ 16:35   0:00 ffmpeg -loglevel warning -rtsp_transport tcp -vcodec h264 -i rtsp://admin:xxxx@192.168.1.131:554/Streaming/Channels/102 -pix_fmt bgr24 -f rawvideo pipe:
root      220432  0.0  0.0   4028  2092 pts/9    S+   16:35   0:00 grep --color=auto ffmpeg
```
看到只有一个ffmpeg 在后台，应该是 child_process， 主进程的应该已经释放了。

**Comment by Pengtap** [comment]
好的，那应该是我的版本太老了，我去更新下

**Comment by chenxinfeng4** [comment]
Stream 还是一个比较新的特性，近几个月才开始完善的。欢迎star 项目，欢迎反馈bug。

**Comment by Pengtap** [comment]
嗯嗯，一定
