### ISSUE TITLE
whats the example of pip install ffmpegcv[cuda] whats cuda here?

### ISSUE THREAD

**Issue by aloksharma1** [chenxinfeng4/ffmpegcv#46]
Hello,
Python newbie here, i want to know what i have to pass in cuda here

recommand when using cuda
 pip install ffmpegcv[cuda] 
 
 is it my nvidia driver version, toolkit version or cudnn path, i am on windows 11.

**Comment by chenxinfeng4** [comment]
you can install the ffmpegcv step by step.

First make sure you have add the ffmpeg into your path. You can do that by conda or manually add the FFMPEG/BIN to your windows 11 environment PATH.

```cmd
# In the system cmd window
ffmpeg -version 
```

Then install the ffmpegcv by pip.
```bash
pip install ffmpegcv
```

**Comment by aloksharma1** [comment]
oh already done that than, thanks another issue is i need to extract frame properties for camera calibration (i want to stabilize shaky camera feed) but i don't see a documentation for this lib, and OpenCV `cap.info` is not working with this library.

**Comment by chenxinfeng4** [comment]
The `cap.info` is not the frame property in OpenCV neither, it should be the video property. If you want the video info, you can just print the `cap` of a ffmpegcv.VideoCapture* instance. You will see the `width/heigh/fps/duration/counts` of the video.

`print(cap);dir(cap)`

**Comment by chenxinfeng4** [comment]
Since no more question, this issue will be closed.
