### ISSUE TITLE
Using the crop_xywh to extract a specific region from a video and save it as an image

### ISSUE THREAD

**Issue by zhuyuhang4** [chenxinfeng4/ffmpegcv#49]
Hello, thank you for such an excellent package！
There are flickering lights in my video, and I want to find the frames where the light is on. I first used ImageJ to find the ROI (Region of Interest) for the light, but I found that the ROI images saved for the frames where the light is on are not bright. It seems that the average grayscale value calculated for the entire video within the ROI is correct.

![8b773ec9a7893834af75cfa73e043db](https://github.com/user-attachments/assets/e6b6b5de-a126-4e24-bc0e-a48f78f8500b)

![a3c59e59850a1c0a5ebfc7b52b098e0](https://github.com/user-attachments/assets/08202e76-d7b5-4d0d-83c4-5afc3c09b3b4)

![66b9b8125aea32dae053df2d386ac56](https://github.com/user-attachments/assets/35598a2a-e97f-4027-bce2-92ee37ca4b18)

**Comment by chenxinfeng4** [comment]
The 'crop_xywh' should be all even number. Change it to the [624,44,6,6]. Similarly, the 'resize' and 'VideoWriter' should also use even size of frame.

This 'even number' issue will be warning to developers in next release.
