### ISSUE TITLE
how to use web camera?

### ISSUE THREAD

**Issue by 1973ai** [chenxinfeng4/ffmpegcv#5]
cap = ffmpegcv.VideoCaptureCAM("rtsp://", (1280, 720))
this line can not running.

**Comment by chenxinfeng4** [comment]
The VideoCaptureCAM is an **experimental** feature for **USB CAMERA**. I don't have a web camera in my hand.  If you want to use rtsp web camera, you can go to the `ffmpegcv/ffmpeg_reader_camera.py`
```python
        args = (f'ffmpeg -loglevel warning '
                f' -f dshow -video_size {vid.origin_width}x{vid.origin_height} '
                f' -i video="{camname}" '
                f' {filteropt} -pix_fmt {pix_fmt} -f rawvideo pipe:')
```

Change the code to something like this and fix the bug if any.
```python
        args = (f'ffmpeg -loglevel warning '
                f' -i rtsp://user@passwd:192.168.0.2:port/CH002.sdp'
                f' {filteropt} -pix_fmt {pix_fmt} -f rawvideo pipe:')
```

The rtsp camera and usb camera work really different with video file. The most one is that camera fps may be faster than your post-processing, which may cause lag and out of buffer issues. So it needs **drop frames** to keep as real time as possible. Please make sure 'drop frames' is under your consideration. Besides, rtsp camera seems very laggy (1-2sec) than usb camera.

```python
        vid.q = Queue(maxsize=30)  # change to small buffer size to keep real time
        producer = ProducerThread(vid, vid.q)
```
