### ISSUE TITLE
RuntimeError: No NVIDIA GPU found despite compiling ffmpeg with CUDA support on Google Colab GPU Instance

### ISSUE THREAD

**Issue by avadhut-00** [chenxinfeng4/ffmpegcv#7]
I have configured ffmpeg with GPU Support on Google Colab GPU Instance using the  [Nvidia Official Docs](https://docs.nvidia.com/video-technologies/video-codec-sdk/ffmpeg-with-nvidia-gpu/) but despite this I was unable to read a video utilizing GPU method **ffmpegcv.VideoCaptureNV()** .Also the ffmpeg build with CUDA support is successful and verified.

I have made my Google Colab Notebook public where all of the steps are implemented. Could you please have a look at it and advise me on a possible way to circumvent this issue.

[FFMPEGCV Install on Google Colab GPU Instance](https://colab.research.google.com/drive/1N_EKsNxkJyN2vI2yxH1REUWRr62ICdLX?usp=sharing)

**Comment by chenxinfeng4** [comment]
Ohh, I see the bug. Here is my test enviroment:

![image](https://user-images.githubusercontent.com/17546446/226080868-e91356db-ffde-40e3-98de-21a157ac9a7c.png)

And there's the colab:
![image](https://user-images.githubusercontent.com/17546446/226080970-78844c9d-3109-4696-aa8e-44644f133347.png)

The ffmpegcv checked the `NVIDIA` token, which is not shown in the Telsa gpu. I'll fix that.
```python
def get_num_NVIDIA_GPUs():
    cmd = 'ffmpeg -f lavfi -i nullsrc -c:v h264_nvenc -gpu list -f null -'
    p = Popen(cmd.split(), shell=False, stdin=PIPE, stdout=PIPE, stderr=PIPE)
    stdout, stderr = p.communicate(b"")
    p.stdin.close()
    p.stdout.close()
    p.terminate()
    pattern = re.compile(r'GPU #\d+ - < NVIDIA')   <===BUG
    nv_info = pattern.findall(stderr.decode())
    num_gpu = len(nv_info)
    return num_gpu
```

**Comment by chenxinfeng4** [comment]
It works for the colab now. However, the GPU decoding is even a bit slower than the CPU.

![image](https://user-images.githubusercontent.com/17546446/226081861-0ff12514-a814-4aeb-9998-c1041b530a34.png)

**Comment by avadhut-00** [comment]
What speed-ups are normally expected when performing a GPU Vs CPU Decoding with ffmpegcv. Are the slow speed on GPU attributable to ffmpeg  build on this particular GPU model or ffmpegcv ?  Could you provide some benchmark numbers from your test environment ?

**Comment by avadhut-00** [comment]
![Video_Reading_Nvidia_A100](https://user-images.githubusercontent.com/112175709/226097457-87b65a8f-9833-4be1-9bcd-c77be4d49988.PNG)

On a Nvidia A100 I received about video read speeds of 830 it/sec both on the CPU and the GPU.

**Comment by avadhut-00** [comment]
![Video_Reading_Nvidia_Tesla_T4](https://user-images.githubusercontent.com/112175709/226098972-d6b2ab66-1147-4d26-a06f-3173bfe1e4bf.PNG)

On a Nvidia Tesla T4 I received video read speeds as mentioned in the pic for CPU & GPU

**Comment by avadhut-00** [comment]
There is almost 3x speed improvement in both CPU & GPU on Nvidia A100 Instances. How would one go about explaining this scenario ?

**Comment by chenxinfeng4** [comment]
The speed difference of Tesla CPU vs A100 CPU may depend on the **CPU cores**. I test that code in my linux server, it's about **650 it/s in CPU, 553 it/s in GPU RTX4090**.  

But the GPU reader is still slower than CPU reader in all platforms. The ffmpegcv didn't make the most use of GPU capability somehow (the NVDEC is not 100% occupied). The GPU reader is faster when using **CROP, RESIZE** and **PAD** operations.
