### ISSUE TITLE
Video Writer is not fast as expected. even slower..

### ISSUE THREAD

**Issue by TaekyungKi** [chenxinfeng4/ffmpegcv#9]
I run the following comparison code with the line profiler of python library. (Python version 3.8.5 / FFMPEG version 4.2.7-0ubuntu0.1)

In this scenario, we assume that all images (389 .png) are in the list with RGB order, each of which is a (high) resolution of 2160x3840. Therefore in `make_video_ffmpegcv`, i assigned `pix_fmt="rgb24"`. I also checked that the gpu memories are assigned during the running `make_video_ffmpegcv`. Is there anything that i missed for the function `make_video_ffmpegcv` ?

Best,

<img width="888" alt="스크린샷 2023-03-21 오전 11 50 33" src="https://user-images.githubusercontent.com/55676509/226507339-8bc5dbdf-1238-4640-8ed9-f65cae71c3e8.png">

<img width="1188" alt="스크린샷 2023-03-21 오전 11 52 19" src="https://user-images.githubusercontent.com/55676509/226507515-7f848b2e-4a86-4c8a-8889-eadb5c0b943f.png">

**Comment by TaekyungKi** [comment]
I also tested on frames of 256x256 resolution with the same number of video frames. It is not the problem of high resolution !
<img width="1172" alt="스크린샷 2023-03-21 오후 12 06 43" src="https://user-images.githubusercontent.com/55676509/226508939-5d23454e-9b2a-43cd-9bee-87e98a3b3257.png">

**Comment by chenxinfeng4** [comment]
The opencv cann't write the h264/h265 video (I didn't find a simple way). The `mp4v` is an old guy that matches opencv.  **The `h264` codec is not the same as `mp4v` nor `mjpeg`.**  The `h264` & `h265=hevc` is better in quality and little in file storage, which is preferred  in the Youtube and other video web sites.

The ffmpegcv-cpu writer supports `mpeg` `mjpeg` `h264` `h265(hevc)` and so on, the gpu writer only for  `h264` `h265(hevc)`.

**Comment by TaekyungKi** [comment]
I tested the same frames of video, but in the 'jpeg' extension. And I changed the codec for gpu writer. But there are still no improvements...

**Comment by chenxinfeng4** [comment]
Can you post your code? Just like this.

```python
import tqdm
import numpy as np
import ffmpegcv

out = cv2.VideoWriter('output.mp4',fourcc, cap_gpu.fps, (1280,720))

for _ in tqdm.trange(1000):
    frame = np.random.randint(0, 255, (720,1280,3), dtype='uint8')
    out.write(frame)
out.release
```

**Comment by TaekyungKi** [comment]
Here is my code.
```python
import ffmpegcv

def make_video_ffmpegcv(frame_list, video_path, frame_size):
    video = ffmpegcv.VideoWriterNV(video_path, 'hevc_nvenc', fps = 25, frameSize=frame_size, pix_fmt = "rgb24")
    video.preset = 'default'
    for frame in frame_list:
        video.write(frame)
    video.release()
``` 

where `frame_list` is a list of frames (RGB) of `np.array` and `video_path` is the result video path (.mp4), frame_size the  tuple of video resolution (width, height).

**Comment by chenxinfeng4** [comment]
I see this's the ffmegcv-writer-gpu, what else did you try?

**Comment by TaekyungKi** [comment]
I tried the usual opencv method like
```python
import cv2

def make_video_opencv(frame_list, video_path, frame_size):
    video = cv2.VideoWriter(video_path, cv2.VideoWriter_fourcc('m', 'p', '4', 'v'), fps=25, frameSize=frame_size)
    for frame in frame_list:
        video.write(frame)
    video.release()
```
In here, `frame_list` is a list of frames (BGR order!). I compared it to the function `make_video_ffmpegcv` right above.
I tried changing all supported codecs, changing `VideoWriterNV`to `VideoWriter` in `ffmpegcv', and changing the image format (.png to .jpg).

My point is `VideoWriterNV` (using GPU) is slower than the usual `VideoWriter` in OpenCV (using CPU), as shown in the line_profiler results in the top figure.

**Comment by chenxinfeng4** [comment]
Different codecs have different speed & quality. The `hevc` is better than `mp4v` in quality, but opencv writer didn't support it. See the `$ffmpeg -encoders` for codecs available in ffmpeg.VideoWriter.

**Comment by TaekyungKi** [comment]
Ah, I got it too. Thank you !
Then, is there any way to use `ffmpegcv` (for faster video writing) and conserve the quality comparable with `mp4v`?
I saw there are two available codecs for it. is it right?

**Comment by chenxinfeng4** [comment]
The `ffmepgcv` support all `ffmpeg` codecs. So you can search the fast codec by *ffmpeg -encoders*. In practical, you can use `mpeg4`(same as mp4v in opencv) or `mjpeg` for the sake of speed. In these two codes, the ffmpegcv is similar to or slower than opencv -- opencv is good enough.  The `mjpeg` and `mpeg4` do not work in GPU, so can not speed up.

The NVIDIA  GPU only works for `h264`, `h265` codecs. So that the `ffmpegcv.VideoWriterNV` only support these codes. See the NVIDIA encoders, and `ffmpeg -encoders | grep nvenc`.

In all, opencv is good enough in speed. And the ffmpegcv is better in quality control.

**Comment by TaekyungKi** [comment]
Ah! Thank you for your clear comment. It helps me. I will close this issue.
